-- STAGING DEVELOPMENT / SUPERSEDED FOR PRODUCTION.
-- Production source of truth: supabase-phase-kpi2-final-consolidated.sql.
-- Do not run this file together with the consolidated migration.
-- KPI-2 staging-only foundation: submissions, event claims, private evidence,
-- event-level review and provisional approved actual.
-- Dependencies: P0-A, P0-B and KPI-1 are already applied.
-- Additive only. Legacy kpi_rules/kpi_proposals are not modified.

begin;

-- ---------------------------------------------------------------------------
-- 1. Additive KPI-1 extensions
-- ---------------------------------------------------------------------------

alter table public.kpi_definitions
  add column if not exists aggregation_mode text not null default 'COUNT',
  add column if not exists max_images_per_event integer not null default 2,
  add column if not exists location_required boolean not null default false,
  add column if not exists timestamp_required boolean not null default true;

alter table public.kpi_assignments
  add column if not exists score_enabled boolean not null default true;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'kpi_definitions_aggregation_mode_check') then
    alter table public.kpi_definitions add constraint kpi_definitions_aggregation_mode_check
      check (aggregation_mode in ('COUNT', 'SUM'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'kpi_definitions_max_images_check') then
    alter table public.kpi_definitions add constraint kpi_definitions_max_images_check
      check (max_images_per_event between 0 and 2);
  end if;
end $$;

create or replace function public.crm_kpi_definition_snapshot(p_definition public.kpi_definitions)
returns jsonb
language sql
security definer
set search_path = public
stable
as $$
  select jsonb_build_object(
    'code', p_definition.code,
    'name', p_definition.name,
    'description', coalesce(p_definition.description, ''),
    'kpi_type', p_definition.kpi_type,
    'source_metric_key', p_definition.source_metric_key,
    'unit', p_definition.unit,
    'submission_mode', p_definition.submission_mode,
    'evidence_required', p_definition.evidence_required,
    'aggregation_mode', p_definition.aggregation_mode,
    'max_images_per_event', p_definition.max_images_per_event,
    'location_required', p_definition.location_required,
    'timestamp_required', p_definition.timestamp_required,
    'definition_version', p_definition.version,
    'snapshotted_at', now()
  );
$$;
revoke all on function public.crm_kpi_definition_snapshot(public.kpi_definitions)
  from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 2. KPI-2 tables
-- ---------------------------------------------------------------------------

create table if not exists public.kpi_submissions (
  id uuid primary key default gen_random_uuid(),
  assignment_id uuid not null references public.kpi_assignments(id) on delete restrict,
  submission_no bigint generated by default as identity,
  attempt_no integer not null default 1,
  request_id uuid not null,
  submitted_by_user_id text not null references public.app_users(id) on delete restrict,
  submitted_at timestamptz not null default now(),
  sale_note text,
  status text not null default 'OPEN_REVIEW',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  lock_version integer not null default 1,
  constraint kpi_submissions_actor_request_unique unique (submitted_by_user_id, request_id),
  constraint kpi_submissions_attempt_check check (attempt_no > 0),
  constraint kpi_submissions_status_check check (status in ('OPEN_REVIEW', 'PARTIALLY_REVIEWED', 'COMPLETED')),
  constraint kpi_submissions_version_check check (lock_version > 0)
);

create table if not exists public.kpi_submission_events (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null references public.kpi_submissions(id) on delete restrict,
  assignment_id uuid not null references public.kpi_assignments(id) on delete restrict,
  source_type text not null,
  source_id text,
  source_event_key text not null,
  event_at timestamptz not null,
  actor_user_id text not null references public.app_users(id) on delete restrict,
  customer_id text references public.customers(id) on delete set null,
  claimed_value numeric not null default 1,
  approved_value numeric,
  event_snapshot jsonb not null default '{}'::jsonb,
  location_snapshot jsonb,
  possible_duplicate boolean not null default false,
  duplicate_context jsonb not null default '[]'::jsonb,
  status text not null default 'PENDING',
  review_reason_code text,
  manager_note text,
  reviewed_by_user_id text references public.app_users(id) on delete restrict,
  reviewed_at timestamptz,
  supersedes_event_id uuid references public.kpi_submission_events(id) on delete restrict,
  root_event_id uuid references public.kpi_submission_events(id) on delete restrict,
  revision_no integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  lock_version integer not null default 1,
  constraint kpi_submission_events_source_type_check check (source_type in ('MANUAL', 'CARE_LOG', 'CUSTOMER', 'DEAL', 'SHOWROOM_VISIT', 'OTHER')),
  constraint kpi_submission_events_source_key_check check (nullif(btrim(source_event_key), '') is not null),
  constraint kpi_submission_events_value_check check (claimed_value > 0),
  constraint kpi_submission_events_snapshot_check check (jsonb_typeof(event_snapshot) = 'object'),
  constraint kpi_submission_events_location_check check (location_snapshot is null or jsonb_typeof(location_snapshot) = 'object'),
  constraint kpi_submission_events_duplicate_context_check check (jsonb_typeof(duplicate_context) = 'array'),
  constraint kpi_submission_events_status_check check (status in ('PENDING', 'NEEDS_REVISION', 'APPROVED', 'REJECTED')),
  constraint kpi_submission_events_reason_check check (review_reason_code is null or review_reason_code in ('DUPLICATE', 'INVALID_EVIDENCE', 'MISSING_LOCATION', 'MISSING_TIMESTAMP', 'INCOMPLETE_INFORMATION', 'NOT_NEW', 'OUT_OF_SCOPE', 'OTHER')),
  constraint kpi_submission_events_review_shape_check check (
    (status = 'PENDING' and reviewed_by_user_id is null and reviewed_at is null and approved_value is null)
    or (status = 'APPROVED' and reviewed_by_user_id is not null and reviewed_at is not null and approved_value is not null)
    or (status in ('NEEDS_REVISION', 'REJECTED') and reviewed_by_user_id is not null and reviewed_at is not null and approved_value is null)
  ),
  constraint kpi_submission_events_revision_check check (revision_no > 0),
  constraint kpi_submission_events_version_check check (lock_version > 0)
);

create unique index if not exists kpi_submission_events_root_dedupe_idx
  on public.kpi_submission_events(assignment_id, source_type, source_event_key)
  where supersedes_event_id is null;
create unique index if not exists kpi_submission_events_single_revision_idx
  on public.kpi_submission_events(supersedes_event_id)
  where supersedes_event_id is not null;

create table if not exists public.kpi_evidence (
  id uuid primary key,
  assignment_id uuid not null references public.kpi_assignments(id) on delete restrict,
  event_id uuid references public.kpi_submission_events(id) on delete restrict,
  bucket text not null default 'kpi2-evidence',
  object_path text not null unique,
  original_name text not null,
  mime_type text not null,
  size_bytes bigint not null,
  sha256 text not null,
  uploaded_by_user_id text not null references public.app_users(id) on delete restrict,
  uploaded_at timestamptz not null default now(),
  attached_at timestamptz,
  status text not null default 'STAGED',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  lock_version integer not null default 1,
  constraint kpi_evidence_bucket_check check (bucket = 'kpi2-evidence'),
  constraint kpi_evidence_path_check check (object_path like 'kpi2/%'),
  constraint kpi_evidence_name_check check (nullif(btrim(original_name), '') is not null),
  constraint kpi_evidence_mime_check check (mime_type in ('image/jpeg', 'image/webp')),
  constraint kpi_evidence_size_check check (size_bytes between 1 and 1572864),
  constraint kpi_evidence_sha_check check (sha256 ~ '^[a-f0-9]{64}$'),
  constraint kpi_evidence_status_check check (status in ('STAGED', 'ATTACHED', 'QUARANTINED', 'ARCHIVED')),
  constraint kpi_evidence_attach_shape_check check ((status = 'ATTACHED' and event_id is not null and attached_at is not null) or status <> 'ATTACHED'),
  constraint kpi_evidence_version_check check (lock_version > 0)
);

create table if not exists public.kpi_action_requests (
  id uuid primary key default gen_random_uuid(),
  actor_user_id text not null references public.app_users(id) on delete restrict,
  action text not null,
  request_id uuid not null,
  response jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint kpi_action_requests_unique unique (actor_user_id, action, request_id),
  constraint kpi_action_requests_action_check check (nullif(btrim(action), '') is not null),
  constraint kpi_action_requests_response_check check (jsonb_typeof(response) = 'object')
);

create index if not exists kpi_submissions_assignment_time_idx on public.kpi_submissions(assignment_id, submitted_at desc);
create index if not exists kpi_events_assignment_status_idx on public.kpi_submission_events(assignment_id, status, event_at desc);
create index if not exists kpi_events_submission_idx on public.kpi_submission_events(submission_id, created_at);
create index if not exists kpi_events_source_lookup_idx on public.kpi_submission_events(source_type, source_event_key);
create index if not exists kpi_evidence_event_idx on public.kpi_evidence(event_id, status);
create index if not exists kpi_evidence_staged_ttl_idx on public.kpi_evidence(status, uploaded_at) where status = 'STAGED';

-- ---------------------------------------------------------------------------
-- 3. Direct-write guards, RLS and private Storage
-- ---------------------------------------------------------------------------

drop trigger if exists kpi_submissions_guard_direct_write on public.kpi_submissions;
create trigger kpi_submissions_guard_direct_write before insert or update or delete on public.kpi_submissions
for each row execute function public.crm_kpi_guard_direct_write();
drop trigger if exists kpi_submission_events_guard_direct_write on public.kpi_submission_events;
create trigger kpi_submission_events_guard_direct_write before insert or update or delete on public.kpi_submission_events
for each row execute function public.crm_kpi_guard_direct_write();
drop trigger if exists kpi_evidence_guard_direct_write on public.kpi_evidence;
create trigger kpi_evidence_guard_direct_write before insert or update or delete on public.kpi_evidence
for each row execute function public.crm_kpi_guard_direct_write();
drop trigger if exists kpi_action_requests_guard_direct_write on public.kpi_action_requests;
create trigger kpi_action_requests_guard_direct_write before insert or update or delete on public.kpi_action_requests
for each row execute function public.crm_kpi_guard_direct_write();

create or replace function public.crm_kpi_can_read_assignment_runtime(p_assignment_id uuid)
returns boolean language sql security definer set search_path = public stable
as $$
  select public.crm_kpi_is_business_manager() or exists (
    select 1 from public.kpi_assignments a join public.kpi_periods p on p.id = a.period_id
    where a.id = p_assignment_id and a.employee_id = public.crm_current_app_user_id()
      and a.assignment_status = 'ASSIGNED' and p.status in ('ACTIVE', 'CLOSED')
  );
$$;

create or replace function public.crm_kpi_can_read_event(p_event_id uuid)
returns boolean language sql security definer set search_path = public stable
as $$
  select exists (select 1 from public.kpi_submission_events e where e.id = p_event_id
    and public.crm_kpi_can_read_assignment_runtime(e.assignment_id));
$$;

revoke all on function public.crm_kpi_can_read_assignment_runtime(uuid) from public, anon;
revoke all on function public.crm_kpi_can_read_event(uuid) from public, anon;
grant execute on function public.crm_kpi_can_read_assignment_runtime(uuid) to authenticated;
grant execute on function public.crm_kpi_can_read_event(uuid) to authenticated;

alter table public.kpi_submissions enable row level security;
alter table public.kpi_submission_events enable row level security;
alter table public.kpi_evidence enable row level security;
alter table public.kpi_action_requests enable row level security;

drop policy if exists "kpi2 submissions canonical read" on public.kpi_submissions;
create policy "kpi2 submissions canonical read" on public.kpi_submissions for select to authenticated
using (public.crm_kpi_can_read_assignment_runtime(assignment_id));
drop policy if exists "kpi2 events canonical read" on public.kpi_submission_events;
create policy "kpi2 events canonical read" on public.kpi_submission_events for select to authenticated
using (public.crm_kpi_can_read_assignment_runtime(assignment_id));
drop policy if exists "kpi2 evidence canonical read" on public.kpi_evidence;
create policy "kpi2 evidence canonical read" on public.kpi_evidence for select to authenticated
using (uploaded_by_user_id = public.crm_current_app_user_id() or public.crm_kpi_is_business_manager());

revoke all on public.kpi_submissions, public.kpi_submission_events, public.kpi_evidence, public.kpi_action_requests from public, anon, authenticated;
grant select on public.kpi_submissions, public.kpi_submission_events, public.kpi_evidence to authenticated;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('kpi2-evidence', 'kpi2-evidence', false, 1572864, array['image/jpeg', 'image/webp'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "kpi2 evidence owner insert" on storage.objects;
create policy "kpi2 evidence owner insert" on storage.objects for insert to authenticated
with check (bucket_id = 'kpi2-evidence' and (storage.foldername(name))[1] = 'kpi2'
  and (storage.foldername(name))[2] = public.crm_current_app_user_id());
drop policy if exists "kpi2 evidence canonical select" on storage.objects;
create policy "kpi2 evidence canonical select" on storage.objects for select to authenticated
using (bucket_id = 'kpi2-evidence' and exists (
  select 1 from public.kpi_evidence e where e.bucket = bucket_id and e.object_path = name
    and (e.uploaded_by_user_id = public.crm_current_app_user_id() or public.crm_kpi_is_business_manager())
));
drop policy if exists "kpi2 evidence staged owner delete" on storage.objects;
create policy "kpi2 evidence staged owner delete" on storage.objects for delete to authenticated
using (bucket_id = 'kpi2-evidence' and exists (
  select 1 from public.kpi_evidence e where e.bucket = bucket_id and e.object_path = name
    and e.status = 'STAGED' and e.uploaded_by_user_id = public.crm_current_app_user_id()
));

-- ---------------------------------------------------------------------------
-- 4. Definition and assignment extension RPCs
-- ---------------------------------------------------------------------------

create or replace function public.crm_kpi_create_definition_v2(
  p_code text, p_name text, p_description text, p_kpi_type text,
  p_source_metric_key text, p_unit text, p_submission_mode text,
  p_evidence_required boolean, p_aggregation_mode text,
  p_max_images_per_event integer, p_location_required boolean,
  p_timestamp_required boolean
) returns jsonb language plpgsql security definer set search_path = public as $$
declare v_actor text := public.crm_current_app_user_id(); v_row public.kpi_definitions%rowtype;
  v_code text := upper(btrim(coalesce(p_code,''))); v_type text := upper(btrim(coalesce(p_kpi_type,'')));
  v_mode text := upper(btrim(coalesce(p_submission_mode,'EVENT_CLAIM'))); v_agg text := upper(btrim(coalesce(p_aggregation_mode,'COUNT')));
begin
  if not public.crm_kpi_is_business_manager() then raise exception using errcode='42501', message='Chỉ manager/admin/owner được tạo KPI.'; end if;
  if v_code !~ '^[A-Z][A-Z0-9_]{1,63}$' or nullif(btrim(coalesce(p_name,'')),'') is null or nullif(btrim(coalesce(p_unit,'')),'') is null
    then raise exception using errcode='22023', message='Mã, tên hoặc đơn vị KPI không hợp lệ.'; end if;
  if v_type not in ('AUTO','MANUAL','HYBRID') or v_mode <> 'EVENT_CLAIM' or v_agg not in ('COUNT','SUM')
    then raise exception using errcode='22023', message='Cấu hình loại/aggregation KPI không hợp lệ.'; end if;
  if coalesce(p_max_images_per_event,2) not between 0 and 2 then raise exception using errcode='22023', message='Tối đa 0-2 ảnh mỗi event.'; end if;
  perform set_config('crm.kpi_write','on',true);
  insert into public.kpi_definitions(code,name,description,kpi_type,source_metric_key,unit,submission_mode,evidence_required,
    aggregation_mode,max_images_per_event,location_required,timestamp_required,active,created_by_user_id,updated_by_user_id)
  values(v_code,btrim(p_name),nullif(btrim(coalesce(p_description,'')),''),v_type,nullif(btrim(coalesce(p_source_metric_key,'')),''),btrim(p_unit),
    v_mode,coalesce(p_evidence_required,false),v_agg,coalesce(p_max_images_per_event,2),coalesce(p_location_required,false),
    coalesce(p_timestamp_required,true),true,v_actor,v_actor) returning * into v_row;
  perform public.crm_kpi_write_audit('definition_create','kpi_definitions',v_row.id::text,jsonb_build_object('after',to_jsonb(v_row),'phase','KPI-2'));
  return to_jsonb(v_row);
exception when unique_violation then raise exception using errcode='23505', message='Mã KPI đã tồn tại.';
end $$;

create or replace function public.crm_kpi_update_assignment_options(
  p_assignment_id uuid, p_score_enabled boolean, p_expected_assignment_version integer, p_expected_period_version integer
) returns jsonb language plpgsql security definer set search_path = public as $$
declare v_old public.kpi_assignments%rowtype; v_new public.kpi_assignments%rowtype; v_period public.kpi_periods%rowtype;
begin
  if not public.crm_kpi_is_business_manager() then raise exception using errcode='42501', message='Không có quyền sửa tùy chọn KPI.'; end if;
  select * into v_old from public.kpi_assignments where id=p_assignment_id for update;
  if v_old.id is null then raise exception using errcode='P0002', message='Không tìm thấy assignment.'; end if;
  select * into v_period from public.kpi_periods where id=v_old.period_id for update;
  if v_period.status <> 'DRAFT' then raise exception using errcode='55000', message='Chỉ kỳ DRAFT được sửa.'; end if;
  if v_old.lock_version <> p_expected_assignment_version or v_period.version <> p_expected_period_version then
    raise exception using errcode='P0001', message='KPI_VERSION_CONFLICT: Dữ liệu đã thay đổi.'; end if;
  perform set_config('crm.kpi_write','on',true);
  update public.kpi_assignments set score_enabled=coalesce(p_score_enabled,true),updated_at=now(),lock_version=lock_version+1
    where id=p_assignment_id returning * into v_new;
  update public.kpi_periods set version=version+1,updated_at=now() where id=v_old.period_id;
  perform public.crm_kpi_write_audit('assignment_options_update','kpi_assignments',v_new.id::text,
    jsonb_build_object('before',to_jsonb(v_old),'after',to_jsonb(v_new),'periodVersion',v_period.version+1));
  return to_jsonb(v_new)||jsonb_build_object('periodVersion',v_period.version+1);
end $$;

-- ---------------------------------------------------------------------------
-- 5. Evidence staging and source adapters
-- ---------------------------------------------------------------------------

create or replace function public.crm_kpi_stage_evidence(
  p_evidence_id uuid, p_assignment_id uuid, p_object_path text,
  p_original_name text, p_mime_type text, p_size_bytes bigint, p_sha256 text
) returns jsonb language plpgsql security definer set search_path = public, storage as $$
declare v_actor text := public.crm_current_app_user_id(); v_assignment public.kpi_assignments%rowtype;
  v_period public.kpi_periods%rowtype; v_object storage.objects%rowtype; v_row public.kpi_evidence%rowtype;
begin
  if not public.crm_is_active_user() then raise exception using errcode='42501', message='Tài khoản không hoạt động.'; end if;
  select * into v_assignment from public.kpi_assignments where id=p_assignment_id and employee_id=v_actor and assignment_status='ASSIGNED';
  if v_assignment.id is null then raise exception using errcode='42501', message='Bạn chỉ upload minh chứng cho KPI của mình.'; end if;
  select * into v_period from public.kpi_periods where id=v_assignment.period_id;
  if v_period.status <> 'ACTIVE' then raise exception using errcode='55000', message='Chỉ kỳ KPI ACTIVE nhận minh chứng.'; end if;
  if p_evidence_id is null or p_object_path <> 'kpi2/'||v_actor||'/'||p_evidence_id::text||'/'||regexp_replace(p_original_name,'[^A-Za-z0-9._-]+','_','g') then
    raise exception using errcode='22023', message='Đường dẫn minh chứng không hợp lệ.'; end if;
  if p_mime_type not in ('image/jpeg','image/webp') or p_size_bytes not between 1 and 1572864 or lower(coalesce(p_sha256,'')) !~ '^[a-f0-9]{64}$' then
    raise exception using errcode='22023', message='Ảnh phải là JPEG/WebP, tối đa 1.5MB và có SHA256 hợp lệ.'; end if;
  select * into v_object from storage.objects where bucket_id='kpi2-evidence' and name=p_object_path;
  if v_object.id is null then raise exception using errcode='P0002', message='Không tìm thấy file vừa upload.'; end if;
  perform set_config('crm.kpi_write','on',true);
  insert into public.kpi_evidence(id,assignment_id,bucket,object_path,original_name,mime_type,size_bytes,sha256,uploaded_by_user_id)
  values(p_evidence_id,p_assignment_id,'kpi2-evidence',p_object_path,p_original_name,p_mime_type,p_size_bytes,lower(p_sha256),v_actor)
  returning * into v_row;
  perform public.crm_kpi_write_audit('evidence_stage','kpi_evidence',v_row.id::text,
    jsonb_build_object('assignmentId',p_assignment_id,'bucket',v_row.bucket,'objectPath',v_row.object_path,'sizeBytes',v_row.size_bytes));
  return to_jsonb(v_row);
exception when unique_violation then
  select * into v_row from public.kpi_evidence where id=p_evidence_id and uploaded_by_user_id=v_actor;
  if v_row.id is null then raise exception using errcode='23505', message='Minh chứng đã được dùng.'; end if;
  return to_jsonb(v_row);
end $$;

create or replace function public.crm_kpi_source_snapshot(
  p_assignment_id uuid, p_source_type text, p_source_id text
) returns jsonb language plpgsql security definer set search_path = public stable as $$
declare v_assignment public.kpi_assignments%rowtype; v_period public.kpi_periods%rowtype; v_metric text;
  v_row jsonb; v_actor text := public.crm_current_app_user_id();
begin
  select * into v_assignment from public.kpi_assignments where id=p_assignment_id;
  if v_assignment.id is null or v_assignment.employee_id<>v_actor then raise exception using errcode='42501', message='Assignment không thuộc sale hiện tại.'; end if;
  select * into v_period from public.kpi_periods where id=v_assignment.period_id;
  v_metric := coalesce(v_assignment.definition_snapshot->>'source_metric_key','');
  if v_metric='care_logs_v1' and upper(p_source_type)='CARE_LOG' then
    select jsonb_build_object('source_type','CARE_LOG','source_id',l.id,'source_event_key','care_log:'||l.id,
      'event_at',l.created_at,'customer_id',l.customer_id,'customer_name',l.customer_name,'care_channel',l.care_channel,
      'care_result',l.care_result,'note',l.note,'source_updated_at',l.updated_at)
    into v_row from public.care_logs l join public.customers c on c.id=l.customer_id
    where l.id=p_source_id and not coalesce(l.is_deleted,false) and not coalesce(c.is_deleted,false)
      and c.owner_user_id=v_actor and l.created_at>=v_period.starts_at and l.created_at<v_period.ends_at;
  elsif v_metric='customers_v1' and upper(p_source_type)='CUSTOMER' then
    select jsonb_build_object('source_type','CUSTOMER','source_id',c.id,'source_event_key','customer:'||c.id,
      'event_at',c.created_at,'customer_id',c.id,'customer_name',c.name,'company_name',c.company_name,
      'phone_normalized',c.phone_normalized,'channel',c.channel,'source_updated_at',c.updated_at)
    into v_row from public.customers c where c.id=p_source_id and not coalesce(c.is_deleted,false)
      and c.owner_user_id=v_actor and c.created_at>=v_period.starts_at and c.created_at<v_period.ends_at;
  elsif v_metric='deals_v1' and upper(p_source_type)='DEAL' then
    select jsonb_build_object('source_type','DEAL','source_id',d.id,'source_event_key','deal:'||d.id,
      'event_at',coalesce(d.completed_at,d.created_at),'customer_id',d.customer_id,'customer_name',d.customer_name,
      'amount',coalesce(d.revenue,d.amount,0),'deal_status',d.deal_status,'source_updated_at',d.updated_at)
    into v_row from public.deals d join public.customers c on c.id=d.customer_id
    where d.id=p_source_id and not coalesce(d.is_deleted,false) and c.owner_user_id=v_actor
      and coalesce(d.completed_at,d.created_at)>=v_period.starts_at and coalesce(d.completed_at,d.created_at)<v_period.ends_at;
  else
    raise exception using errcode='22023', message='Source adapter chưa được hỗ trợ cho KPI này.';
  end if;
  if v_row is null then raise exception using errcode='P0002', message='Source event không tồn tại, ngoài kỳ hoặc không thuộc quyền sale.'; end if;
  return v_row;
end $$;
revoke all on function public.crm_kpi_source_snapshot(uuid,text,text) from public,anon,authenticated;

create or replace function public.crm_kpi_list_hybrid_candidates(p_assignment_id uuid)
returns setof jsonb language plpgsql security definer set search_path = public stable as $$
declare v_a public.kpi_assignments%rowtype; v_p public.kpi_periods%rowtype; v_metric text; v_actor text:=public.crm_current_app_user_id();
begin
  select * into v_a from public.kpi_assignments where id=p_assignment_id and employee_id=v_actor and assignment_status='ASSIGNED';
  if v_a.id is null then raise exception using errcode='42501', message='Assignment không thuộc sale hiện tại.'; end if;
  select * into v_p from public.kpi_periods where id=v_a.period_id;
  if v_p.status<>'ACTIVE' then raise exception using errcode='55000', message='Kỳ KPI chưa ACTIVE.'; end if;
  v_metric:=coalesce(v_a.definition_snapshot->>'source_metric_key','');
  if v_metric='care_logs_v1' then
    return query select jsonb_build_object('sourceType','CARE_LOG','sourceId',l.id,'sourceEventKey','care_log:'||l.id,
      'eventAt',l.created_at,'customerId',l.customer_id,'customerName',l.customer_name,'summary',coalesce(l.care_result,l.note,'Chăm sóc khách'),
      'claimed',exists(select 1 from public.kpi_submission_events e where e.assignment_id=v_a.id and e.source_type='CARE_LOG' and e.source_event_key='care_log:'||l.id and e.supersedes_event_id is null))
    from public.care_logs l join public.customers c on c.id=l.customer_id
    where c.owner_user_id=v_actor and not coalesce(c.is_deleted,false) and not coalesce(l.is_deleted,false)
      and l.created_at>=v_p.starts_at and l.created_at<v_p.ends_at order by l.created_at desc limit 200;
  elsif v_metric='customers_v1' then
    return query select jsonb_build_object('sourceType','CUSTOMER','sourceId',c.id,'sourceEventKey','customer:'||c.id,
      'eventAt',c.created_at,'customerId',c.id,'customerName',c.name,'summary',coalesce(c.company_name,c.channel,'Khách mới'),
      'claimed',exists(select 1 from public.kpi_submission_events e where e.assignment_id=v_a.id and e.source_type='CUSTOMER' and e.source_event_key='customer:'||c.id and e.supersedes_event_id is null))
    from public.customers c where c.owner_user_id=v_actor and not coalesce(c.is_deleted,false)
      and c.created_at>=v_p.starts_at and c.created_at<v_p.ends_at order by c.created_at desc limit 200;
  elsif v_metric='deals_v1' then
    return query select jsonb_build_object('sourceType','DEAL','sourceId',d.id,'sourceEventKey','deal:'||d.id,
      'eventAt',coalesce(d.completed_at,d.created_at),'customerId',d.customer_id,'customerName',d.customer_name,
      'summary',coalesce(d.deal_status,'Giao dịch'),'value',coalesce(d.revenue,d.amount,0),
      'claimed',exists(select 1 from public.kpi_submission_events e where e.assignment_id=v_a.id and e.source_type='DEAL' and e.source_event_key='deal:'||d.id and e.supersedes_event_id is null))
    from public.deals d join public.customers c on c.id=d.customer_id where c.owner_user_id=v_actor and not coalesce(d.is_deleted,false)
      and coalesce(d.completed_at,d.created_at)>=v_p.starts_at and coalesce(d.completed_at,d.created_at)<v_p.ends_at
    order by coalesce(d.completed_at,d.created_at) desc limit 200;
  else raise exception using errcode='22023', message='KPI chưa có candidate adapter trong KPI-2.';
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 6. Atomic submission/revision
-- ---------------------------------------------------------------------------

create or replace function public.crm_kpi_submit_events(
  p_assignment_id uuid, p_request_id uuid, p_sale_note text, p_events jsonb
) returns jsonb language plpgsql security definer set search_path = public, storage as $$
declare v_actor text:=public.crm_current_app_user_id(); v_a public.kpi_assignments%rowtype; v_p public.kpi_periods%rowtype;
  v_s public.kpi_submissions%rowtype; v_event jsonb; v_e public.kpi_submission_events%rowtype; v_snapshot jsonb;
  v_source_type text; v_source_id text; v_source_key text; v_event_at timestamptz; v_customer_id text;
  v_value numeric; v_agg text; v_type text; v_evidence jsonb; v_evidence_id uuid; v_count integer; v_location jsonb;
  v_duplicate jsonb; v_ids jsonb:='[]'::jsonb; v_existing jsonb;
begin
  if not public.crm_is_active_user() or p_request_id is null then raise exception using errcode='42501', message='Yêu cầu submit không hợp lệ.'; end if;
  select response into v_existing from public.kpi_action_requests where actor_user_id=v_actor and action='submission_create' and request_id=p_request_id;
  if v_existing is not null then return v_existing; end if;
  select * into v_a from public.kpi_assignments where id=p_assignment_id for update;
  if v_a.id is null or v_a.employee_id<>v_actor or v_a.assignment_status<>'ASSIGNED' then raise exception using errcode='42501', message='Bạn chỉ submit KPI được giao cho mình.'; end if;
  select * into v_p from public.kpi_periods where id=v_a.period_id for share;
  if v_p.status<>'ACTIVE' then raise exception using errcode='55000', message='Chỉ kỳ KPI ACTIVE nhận submission.'; end if;
  if jsonb_typeof(p_events)<>'array' or jsonb_array_length(p_events) not between 1 and 50 then raise exception using errcode='22023', message='Mỗi submission cần 1-50 event.'; end if;
  v_agg:=coalesce(v_a.definition_snapshot->>'aggregation_mode','COUNT'); v_type:=coalesce(v_a.definition_snapshot->>'kpi_type','MANUAL');
  perform set_config('crm.kpi_write','on',true);
  insert into public.kpi_submissions(assignment_id,request_id,submitted_by_user_id,sale_note)
  values(v_a.id,p_request_id,v_actor,nullif(btrim(coalesce(p_sale_note,'')),'')) returning * into v_s;

  for v_event in select value from jsonb_array_elements(p_events) loop
    v_source_type:=upper(btrim(coalesce(v_event->>'sourceType','MANUAL'))); v_source_id:=nullif(btrim(v_event->>'sourceId'),'');
    if v_type in ('HYBRID','AUTO') then
      v_snapshot:=public.crm_kpi_source_snapshot(v_a.id,v_source_type,v_source_id);
      v_source_key:=v_snapshot->>'source_event_key'; v_event_at:=(v_snapshot->>'event_at')::timestamptz;
      v_customer_id:=nullif(v_snapshot->>'customer_id','');
    else
      if v_source_type<>'MANUAL' then raise exception using errcode='22023', message='KPI MANUAL chỉ nhận event MANUAL.'; end if;
      v_source_key:=nullif(btrim(v_event->>'sourceEventKey'),'');
      if v_source_key is null or v_source_key !~ '^manual:[0-9a-f-]{36}$' then raise exception using errcode='22023', message='Manual event key không hợp lệ.'; end if;
      begin v_event_at:=(v_event->>'eventAt')::timestamptz; exception when others then raise exception using errcode='22023', message='Ngày event không hợp lệ.'; end;
      if v_event_at<v_p.starts_at or v_event_at>=v_p.ends_at then raise exception using errcode='22023', message='Event phải nằm trong kỳ KPI.'; end if;
      v_customer_id:=nullif(btrim(v_event->>'customerId'),'');
      v_snapshot:=coalesce(v_event->'eventSnapshot','{}'::jsonb);
      if jsonb_typeof(v_snapshot)<>'object' or nullif(btrim(coalesce(v_snapshot->>'title',v_snapshot->>'description','')),'') is null then
        raise exception using errcode='22023', message='Event MANUAL cần tiêu đề hoặc nội dung.'; end if;
    end if;
    begin v_value:=coalesce((v_event->>'claimedValue')::numeric,1); exception when others then raise exception using errcode='22023', message='Giá trị event không hợp lệ.'; end;
    if v_agg='COUNT' then v_value:=1; elsif v_value<=0 then raise exception using errcode='22023', message='Giá trị SUM phải lớn hơn 0.'; end if;
    v_location:=v_event->'location';
    if coalesce((v_a.definition_snapshot->>'location_required')::boolean,false) and
      (v_location is null or jsonb_typeof(v_location)<>'object' or not(v_location?'latitude') or not(v_location?'longitude') or not(v_location?'accuracy'))
      then raise exception using errcode='22023', message='KPI này bắt buộc vị trí hợp lệ.'; end if;
    v_evidence:=coalesce(v_event->'evidenceIds','[]'::jsonb);
    if jsonb_typeof(v_evidence)<>'array' then raise exception using errcode='22023', message='Danh sách evidence không hợp lệ.'; end if;
    v_count:=jsonb_array_length(v_evidence);
    if v_count>least(2,coalesce((v_a.definition_snapshot->>'max_images_per_event')::integer,2)) then raise exception using errcode='22023', message='Vượt quá số ảnh cho phép mỗi event.'; end if;
    if coalesce((v_a.definition_snapshot->>'evidence_required')::boolean,false) and v_count=0 then raise exception using errcode='22023', message='KPI này bắt buộc ảnh minh chứng.'; end if;
    if v_count<>(select count(*) from jsonb_array_elements_text(v_evidence)) or v_count<>(select count(distinct value) from jsonb_array_elements_text(v_evidence))
      then raise exception using errcode='22023', message='Evidence ID bị trùng hoặc không hợp lệ.'; end if;

    select coalesce(jsonb_agg(jsonb_build_object('eventId',x.id,'employeeId',a.employee_id)),'[]'::jsonb) into v_duplicate
    from public.kpi_submission_events x join public.kpi_assignments a on a.id=x.assignment_id
    where a.period_id=v_a.period_id and a.definition_id=v_a.definition_id and a.employee_id<>v_actor
      and x.source_type=v_source_type and x.source_event_key=v_source_key;
    insert into public.kpi_submission_events(submission_id,assignment_id,source_type,source_id,source_event_key,event_at,actor_user_id,
      customer_id,claimed_value,event_snapshot,location_snapshot,possible_duplicate,duplicate_context)
    values(v_s.id,v_a.id,v_source_type,v_source_id,v_source_key,v_event_at,v_actor,v_customer_id,v_value,v_snapshot,v_location,
      jsonb_array_length(v_duplicate)>0,v_duplicate) returning * into v_e;
    update public.kpi_submission_events set root_event_id=v_e.id where id=v_e.id;
    for v_evidence_id in select value::text::uuid from jsonb_array_elements_text(v_evidence) loop
      update public.kpi_evidence set event_id=v_e.id,status='ATTACHED',attached_at=now(),updated_at=now(),lock_version=lock_version+1
      where id=v_evidence_id and assignment_id=v_a.id and uploaded_by_user_id=v_actor and status='STAGED';
      if not found then raise exception using errcode='22023', message='Evidence không tồn tại, không thuộc bạn hoặc đã được dùng.'; end if;
      perform public.crm_kpi_write_audit('evidence_attach','kpi_evidence',v_evidence_id::text,jsonb_build_object('eventId',v_e.id,'submissionId',v_s.id));
    end loop;
    perform public.crm_kpi_write_audit('event_claim_create','kpi_submission_events',v_e.id::text,
      jsonb_build_object('periodId',v_a.period_id,'assignmentId',v_a.id,'definitionId',v_a.definition_id,'employeeId',v_actor,
        'submissionId',v_s.id,'eventId',v_e.id,'sourceType',v_source_type,'sourceId',v_source_id,'sourceEventKey',v_source_key,
        'claimedValue',v_value,'possibleDuplicate',jsonb_array_length(v_duplicate)>0));
    v_ids:=v_ids||jsonb_build_array(v_e.id);
  end loop;
  v_existing:=jsonb_build_object('submissionId',v_s.id,'status',v_s.status,'eventIds',v_ids,'eventCount',jsonb_array_length(v_ids));
  insert into public.kpi_action_requests(actor_user_id,action,request_id,response) values(v_actor,'submission_create',p_request_id,v_existing);
  perform public.crm_kpi_write_audit('submission_create','kpi_submissions',v_s.id::text,
    jsonb_build_object('periodId',v_a.period_id,'assignmentId',v_a.id,'definitionId',v_a.definition_id,'employeeId',v_actor,
      'submissionId',v_s.id,'requestId',p_request_id,'eventIds',v_ids));
  return v_existing;
exception when unique_violation then
  select response into v_existing from public.kpi_action_requests where actor_user_id=v_actor and action='submission_create' and request_id=p_request_id;
  if v_existing is not null then return v_existing; end if;
  raise exception using errcode='23505', message='Event đã được claim hoặc yêu cầu đã được xử lý.';
end $$;

create or replace function public.crm_kpi_submit_revision(
  p_event_id uuid, p_request_id uuid, p_sale_note text, p_event jsonb
) returns jsonb language plpgsql security definer set search_path = public as $$
declare v_old public.kpi_submission_events%rowtype; v_payload jsonb; v_result jsonb;
begin
  select * into v_old from public.kpi_submission_events where id=p_event_id for update;
  if v_old.id is null or v_old.actor_user_id<>public.crm_current_app_user_id() or v_old.status<>'NEEDS_REVISION' then
    raise exception using errcode='42501', message='Chỉ event NEEDS_REVISION của bạn mới được gửi lại.'; end if;
  v_payload:=jsonb_build_array(coalesce(p_event,'{}'::jsonb)||jsonb_build_object(
    'sourceType',v_old.source_type,'sourceId',v_old.source_id,
    'sourceEventKey','manual:'||gen_random_uuid()::text,
    'eventAt',coalesce(p_event->>'eventAt',v_old.event_at::text),
    'customerId',coalesce(p_event->>'customerId',v_old.customer_id),
    'eventSnapshot',coalesce(p_event->'eventSnapshot',v_old.event_snapshot)||jsonb_build_object('supersedesEventId',v_old.id)
  ));
  v_result:=public.crm_kpi_submit_events(v_old.assignment_id,p_request_id,p_sale_note,v_payload);
  perform set_config('crm.kpi_write','on',true);
  update public.kpi_submission_events set supersedes_event_id=v_old.id,root_event_id=coalesce(v_old.root_event_id,v_old.id),
    revision_no=v_old.revision_no+1 where id=(v_result->'eventIds'->>0)::uuid;
  perform public.crm_kpi_write_audit('event_revision','kpi_submission_events',(v_result->'eventIds'->>0),
    jsonb_build_object('supersedesEventId',v_old.id,'newEventId',v_result->'eventIds'->>0));
  return v_result;
end $$;

-- ---------------------------------------------------------------------------
-- 7. Atomic event review and provisional actual
-- ---------------------------------------------------------------------------

create or replace function public.crm_kpi_refresh_submission_status(p_submission_id uuid)
returns void language plpgsql security definer set search_path = public as $$
declare v_total integer; v_final integer; v_reviewed integer;
begin
  select count(*),count(*) filter(where status in ('APPROVED','REJECTED')),count(*) filter(where status<>'PENDING')
  into v_total,v_final,v_reviewed from public.kpi_submission_events where submission_id=p_submission_id;
  update public.kpi_submissions set status=case when v_total>0 and v_final=v_total then 'COMPLETED'
    when v_reviewed>0 then 'PARTIALLY_REVIEWED' else 'OPEN_REVIEW' end,
    updated_at=now(),lock_version=lock_version+1 where id=p_submission_id;
end $$;
revoke all on function public.crm_kpi_refresh_submission_status(uuid) from public,anon,authenticated;

create or replace function public.crm_kpi_review_events(
  p_request_id uuid, p_rows jsonb, p_decision text, p_reason_code text, p_manager_note text
) returns jsonb language plpgsql security definer set search_path = public as $$
declare v_actor text:=public.crm_current_app_user_id(); v_decision text:=upper(btrim(coalesce(p_decision,'')));
  v_reason text:=upper(nullif(btrim(coalesce(p_reason_code,'')),'')); v_existing jsonb; v_row jsonb;
  v_event public.kpi_submission_events%rowtype; v_ids uuid[]; v_submission_ids uuid[]:='{}'; v_result jsonb:='[]'::jsonb;
begin
  if not public.crm_kpi_is_business_manager() or p_request_id is null then raise exception using errcode='42501', message='Chỉ manager/admin/owner được review KPI.'; end if;
  select response into v_existing from public.kpi_action_requests where actor_user_id=v_actor and action='event_review' and request_id=p_request_id;
  if v_existing is not null then return v_existing; end if;
  if v_decision not in ('APPROVED','REJECTED','NEEDS_REVISION') then raise exception using errcode='22023', message='Decision không hợp lệ.'; end if;
  if jsonb_typeof(p_rows)<>'array' or jsonb_array_length(p_rows) not between 1 and 100 then raise exception using errcode='22023', message='Review cần 1-100 event.'; end if;
  if jsonb_array_length(p_rows)<>(select count(distinct value->>'eventId') from jsonb_array_elements(p_rows)) then raise exception using errcode='22023', message='Danh sách event bị trùng.'; end if;
  if v_decision='REJECTED' and v_reason not in ('DUPLICATE','INVALID_EVIDENCE','MISSING_LOCATION','MISSING_TIMESTAMP','INCOMPLETE_INFORMATION','NOT_NEW','OUT_OF_SCOPE','OTHER')
    then raise exception using errcode='22023', message='Từ chối cần reason code hợp lệ.'; end if;
  if (v_decision='NEEDS_REVISION' or v_reason='OTHER') and nullif(btrim(coalesce(p_manager_note,'')),'') is null
    then raise exception using errcode='22023', message='Cần ghi chú Manager cho NEEDS_REVISION/OTHER.'; end if;
  select array_agg((x->>'eventId')::uuid order by x->>'eventId') into v_ids from jsonb_array_elements(p_rows) x;
  -- Lock all rows in deterministic order, then validate all before the first update.
  perform 1 from public.kpi_submission_events e where e.id=any(v_ids) order by e.id for update;
  if (select count(*) from public.kpi_submission_events where id=any(v_ids))<>cardinality(v_ids) then raise exception using errcode='P0002', message='Có event không tồn tại.'; end if;
  for v_row in select value from jsonb_array_elements(p_rows) loop
    select e.* into v_event from public.kpi_submission_events e join public.kpi_assignments a on a.id=e.assignment_id
      join public.app_users u on u.id=a.employee_id where e.id=(v_row->>'eventId')::uuid and lower(u.role)='sale';
    if v_event.id is null then raise exception using errcode='42501', message='Manager chỉ review KPI của sale.'; end if;
    if v_event.status<>'PENDING' then raise exception using errcode='55000', message='EVENT_VERSION_CONFLICT: Event đã được xử lý.'; end if;
    if v_event.lock_version<>coalesce((v_row->>'expectedVersion')::integer,0) then raise exception using errcode='P0001', message='EVENT_VERSION_CONFLICT: Event đã thay đổi.'; end if;
  end loop;
  perform set_config('crm.kpi_write','on',true);
  for v_row in select value from jsonb_array_elements(p_rows) loop
    update public.kpi_submission_events set status=v_decision,
      approved_value=case when v_decision='APPROVED' then claimed_value else null end,
      review_reason_code=case when v_decision='APPROVED' then null else v_reason end,
      manager_note=nullif(btrim(coalesce(p_manager_note,'')),''),reviewed_by_user_id=v_actor,reviewed_at=now(),updated_at=now(),lock_version=lock_version+1
    where id=(v_row->>'eventId')::uuid returning * into v_event;
    if not(v_event.submission_id=any(v_submission_ids)) then v_submission_ids:=array_append(v_submission_ids,v_event.submission_id); end if;
    perform public.crm_kpi_write_audit(case v_decision when 'APPROVED' then 'event_approve' when 'REJECTED' then 'event_reject' else 'event_needs_revision' end,
      'kpi_submission_events',v_event.id::text,jsonb_build_object('periodId',(select period_id from public.kpi_assignments where id=v_event.assignment_id),
        'assignmentId',v_event.assignment_id,'submissionId',v_event.submission_id,'eventId',v_event.id,'employeeId',v_event.actor_user_id,
        'decision',v_decision,'reason',v_reason,'managerNote',p_manager_note,'after',to_jsonb(v_event)));
    v_result:=v_result||jsonb_build_array(jsonb_build_object('eventId',v_event.id,'status',v_event.status,'lockVersion',v_event.lock_version));
  end loop;
  foreach v_event.submission_id in array v_submission_ids loop perform public.crm_kpi_refresh_submission_status(v_event.submission_id); end loop;
  v_existing:=jsonb_build_object('decision',v_decision,'count',jsonb_array_length(v_result),'events',v_result);
  insert into public.kpi_action_requests(actor_user_id,action,request_id,response) values(v_actor,'event_review',p_request_id,v_existing);
  perform public.crm_kpi_write_audit('bulk_review','kpi_submission_events','bulk',jsonb_build_object('requestId',p_request_id,'decision',v_decision,'reason',v_reason,'events',v_result));
  return v_existing;
end $$;

create or replace function public.crm_kpi_get_assignment_progress(p_period_id uuid default null)
returns table(
  assignment_id uuid, period_id uuid, period_month date, period_status text, definition_id uuid,
  employee_id text, employee_name text, definition_snapshot jsonb, target numeric, score_enabled boolean,
  aggregation_mode text, approved_actual numeric, pending_count bigint, pending_value numeric,
  needs_revision_count bigint, needs_revision_value numeric, rejected_count bigint, rejected_value numeric,
  actual_completion_pct numeric, scoring_completion_pct numeric, has_open_items boolean
) language sql security definer set search_path = public stable as $$
  select a.id,p.id,p.period_month,p.status,a.definition_id,a.employee_id,u.name,a.definition_snapshot,a.target,a.score_enabled,
    coalesce(a.definition_snapshot->>'aggregation_mode','COUNT'),
    coalesce(sum(e.approved_value) filter(where e.status='APPROVED'),0),
    count(e.id) filter(where e.status='PENDING'),coalesce(sum(e.claimed_value) filter(where e.status='PENDING'),0),
    count(e.id) filter(where e.status='NEEDS_REVISION'),coalesce(sum(e.claimed_value) filter(where e.status='NEEDS_REVISION'),0),
    count(e.id) filter(where e.status='REJECTED'),coalesce(sum(e.claimed_value) filter(where e.status='REJECTED'),0),
    round(coalesce(sum(e.approved_value) filter(where e.status='APPROVED'),0)/a.target*100,2),
    least(round(coalesce(sum(e.approved_value) filter(where e.status='APPROVED'),0)/a.target*100,2),100),
    count(e.id) filter(where e.status in ('PENDING','NEEDS_REVISION'))>0
  from public.kpi_assignments a join public.kpi_periods p on p.id=a.period_id join public.app_users u on u.id=a.employee_id
  left join public.kpi_submission_events e on e.assignment_id=a.id
  where a.assignment_status='ASSIGNED' and p.status in ('ACTIVE','CLOSED') and (p_period_id is null or p.id=p_period_id)
    and (public.crm_kpi_is_business_manager() or a.employee_id=public.crm_current_app_user_id())
  group by a.id,p.id,u.name;
$$;

create or replace function public.crm_kpi_get_monthly_scores(p_period_id uuid)
returns table(employee_id text, employee_name text, included_kpi_count bigint, monthly_score numeric, has_open_items boolean)
language sql security definer set search_path = public stable as $$
  select x.employee_id,x.employee_name,count(*) filter(where x.score_enabled),
    round(coalesce(avg(x.scoring_completion_pct) filter(where x.score_enabled),0),2),
    bool_or(x.has_open_items)
  from public.crm_kpi_get_assignment_progress(p_period_id) x group by x.employee_id,x.employee_name;
$$;

-- ---------------------------------------------------------------------------
-- 8. Grants
-- ---------------------------------------------------------------------------

revoke all on function public.crm_kpi_create_definition_v2(text,text,text,text,text,text,text,boolean,text,integer,boolean,boolean) from public,anon;
revoke all on function public.crm_kpi_update_assignment_options(uuid,boolean,integer,integer) from public,anon;
revoke all on function public.crm_kpi_stage_evidence(uuid,uuid,text,text,text,bigint,text) from public,anon;
revoke all on function public.crm_kpi_list_hybrid_candidates(uuid) from public,anon;
revoke all on function public.crm_kpi_submit_events(uuid,uuid,text,jsonb) from public,anon;
revoke all on function public.crm_kpi_submit_revision(uuid,uuid,text,jsonb) from public,anon;
revoke all on function public.crm_kpi_review_events(uuid,jsonb,text,text,text) from public,anon;
revoke all on function public.crm_kpi_get_assignment_progress(uuid) from public,anon;
revoke all on function public.crm_kpi_get_monthly_scores(uuid) from public,anon;
grant execute on function public.crm_kpi_create_definition_v2(text,text,text,text,text,text,text,boolean,text,integer,boolean,boolean) to authenticated;
grant execute on function public.crm_kpi_update_assignment_options(uuid,boolean,integer,integer) to authenticated;
grant execute on function public.crm_kpi_stage_evidence(uuid,uuid,text,text,text,bigint,text) to authenticated;
grant execute on function public.crm_kpi_list_hybrid_candidates(uuid) to authenticated;
grant execute on function public.crm_kpi_submit_events(uuid,uuid,text,jsonb) to authenticated;
grant execute on function public.crm_kpi_submit_revision(uuid,uuid,text,jsonb) to authenticated;
grant execute on function public.crm_kpi_review_events(uuid,jsonb,text,text,text) to authenticated;
grant execute on function public.crm_kpi_get_assignment_progress(uuid) to authenticated;
grant execute on function public.crm_kpi_get_monthly_scores(uuid) to authenticated;

commit;
